@ztpai_HostAddress = https://localhost:7094

GET {{ztpai_HostAddress}}/api/products
Accept: application/json

###

POST {{ztpai_HostAddress}}/api/products
Content-Type: application/json

{
  "Name": "Laptop ASUS TUF A16",
  "Description": "",
  "Price": 4700.0
}

###

@getId = 12
GET {{ztpai_HostAddress}}/api/products/{{getId}}

###

@deleteId = 0
DELETE {{ztpai_HostAddress}}/api/products/{{deleteId}}

###

